---
title: "First Knit"
author: "Jaci"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I was home-schooled for my whole upbringing, through a county program called CHEAV then later called Blue ridge academy. I did indeed graduate through the program as Salutatorian. I think English is best, and it is much easier for me. I did the best in English and Science.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I do have a laptop, it’s a Dell. I would rate myself at a solid 6 for my computer abilities, but I would like to improve that. I also have a good internet connection at my home, it is very reliable.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer to be called Jaci, most of my buddy’s call me by my last name, Heckman though.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to achieve becoming a Lancaster Sheriff for LA County. Going to school for a proposed bachelor in Law, it is my greatest interest, I enjoy Administration of Justice courses so far. My crowning achievement would be to enroll in Bomb technician school in Texas for Arson and Explosive Detective.    
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have been to Ensanada once before on a cruise with my family. I would love to go to Greece or Thailand in the future. I am not a veteran or am currently in the military. If I were drafted I would go Marines, because my brother, father, and fiancé are all marines and I value the work they do.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




